apiVersion: v1
kind: Service
metadata:
  namespace: flinks
  name: flinks
spec:
  selector:
    uri: challenge.domain.local
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32512
