apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: flinks
  name: ingress-flinks
spec:
  rules:
  - host: challenge.domain.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-flinks
            port:
              number: 80
